# Generated by Django 6.0.4 on 2026-04-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
